channels:
  - conda-forge
dependencies:
  - python=3.8
  - cudatoolkit=11.0
  - dask-cuda
  - dask-cudf
  - cudf
  - cuxfilter=22.08.00
  - dash=2.5.1
  - dash-html-components=2.0.0
  - dash-core-components=2.0.0
  - dash-daq=0.5.0
  - dash-bootstrap-components=1.2.0
